#FRONTEND ROUTES#

frontend_contact: 	                ["GET", "/contact", "app\modules\contact\ContactFrontController#contact"]
frontend_contactPost: 	            ["POST", "/contact", "app\modules\contact\ContactFrontController#contact"]